# -*- coding: utf-8 -*-
"""Semana02-05.Operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uGTU82ldsGJe6kziI3tevLuJyvktCFRZ

#SEMANA 02

Giner figueroa Gonzalez

Temas:
  1. Números
  2. Variables
  3. Manejo de cadenas
  4. Ingreso por el teclado
  5. Operadores

5. Operadores
"""

# 5.1 operdores aritmeticos
# se tiene: +, -, *, /, **, %, //

numero1 = 18
numero2 = 3
suma = numero1 + numero2
resta = numero1 - numero2
multiplicacion = numero1 * numero2
division = numero1 / numero2
residuo = numero1 % numero2
cociente = numero1 // numero2
potencia = numero1 ** numero2
print(suma)
print(resta)
print(multiplicacion)
print(division)
print(residuo)
print(cociente)
print(potencia)

#5.2 operadores de asignion
# se tiene: =, +=,
numero = 5
numero=numero+3
print(numero)

#lo mismo se puede hacer con todas los casos, incluso la potencia
numero=5
numero=numero ** 3
print(numero)

#5.3 operadores de comparacion
#se tiene: ==,

#ejemplo de igualdad ==
numero1=5
numero2=2
numero1 == numero2

#con las cadenas funciona igual
nombre1= "Juan"
nombre2= "Juan"
nombre1 == nombre2

#5.4 operadores logicos
#se tiene: and, or, not
numero1= 5
numero2= 6
numero3= 7
numero4= 8

numero1 < numero2

#el not invierte el resultado
not(numero1<numero2)

#tmbien puees utilizar
(numero1<numero2 and numero3<numero4) or (numero3>numero4)

#5.5 operdores de pertenencia
# se tiene: int, not in

#miremos el ejemplo

aula = ["Juan", "Daniel", "Diego"]
alumno1

alumno1

#5.6 operadores de identidad
#se tiene: is, is not

aula1 = ["juan", "daniel", "ruben"]
aula2 = ["juan", "daniel", "ruben"]
aula3 =aula1

aula3 is aula1

aula3 is aula2

aula2 is aula1

aula1.append("Diego")

print(aula1)

print(aula3)

print(aula2)

