# -*- coding: utf-8 -*-
"""Semana02_01.Numeros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kWVZkR4GSbqzkfOvu5Aafd4ZDuuwaxux

Figueroa Gonzales

Temas:
1. Números
2. Variables
3. Manejo de cadenas
4. Ingreso por el teclado
5. Operadores

1. Números
"""

numero=50

type(numero)

numeros=100
cadena=str(numero)
cadena

cadena2="500"

cadena=float(cadena2)

cadena2

