# -*- coding: utf-8 -*-
"""Semana02-04Ingreso por el teclado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1akpZzu2bQqUCVVApD2sVc7_6POMpf2mz

#SEMANA 02

Giner Bush Figueroa Gonzalez

Temas:
  1. Números
  2. Variables
  3. Manejo de cadenas
  4. Ingreso por el teclado
  5. Operadores

4. Ingreso por el teclado
"""

#funcion input()
print("¿cual es tu nombre?")
nombre = input()
print("hola "+ nombre)

#cuando ingrese un valor por teclado lo hace como cadena
print("numero 1: ")
numero1 = input()
print("numero 2: ")
numero2 = input()
numero3 = int(numero1) + int(numero2)
print(f"El resultado es {numero3}")